### ISSUE TITLE
ASDP hanging (looks like on color map)

### ISSUE THREAD

**Issue by lindensmith** [JPLMLIA/OWLS-Autonomy#1]
Installed on a new machine (Catalina 10.5.7, python 3.8) seems to run fine until it gets to generating the ASDP videos:

`Calculate visualizer frames:   0%|                                                                                  | 0/463 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nadeau/opt/anaconda3/envs/CB_autonomy/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/nadeau/Desktop/ClownBarf_machine_learning_tracking/OWLS-Autonomy-master/src/tools/visualizer/render.py", line 57, in gen_visualizer_frame
    plt.register_cmap(cmap=colormap, name='rainbow')
  File "/Users/nadeau/opt/anaconda3/envs/CB_autonomy/lib/python3.8/site-packages/matplotlib/cm.py", line 149, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'rainbow'.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nadeau/opt/anaconda3/envs/CB_autonomy/bin/HELM_pipeline", line 33, in <module>
    sys.exit(load_entry_point('OWLS-Autonomy', 'console_scripts', 'HELM_pipeline')())
  File "/Users/nadeau/Desktop/ClownBarf_machine_learning_tracking/OWLS-Autonomy-master/src/cli/HELM_pipeline.py", line 669, in main
    pipeline_run_step(step_tuple, experiments, batch_outdir, config)
  File "/Users/nadeau/Desktop/ClownBarf_machine_learning_tracking/OWLS-Autonomy-master/src/cli/HELM_pipeline.py", line 528, in pipeline_run_step
    result = experiment_func(experiment, config)
  File "/Users/nadeau/Desktop/ClownBarf_machine_learning_tracking/OWLS-Autonomy-master/src/cli/HELM_pipeline.py", line 215, in asdp_experiment
    visualization(experiment, config, "HELM", config['_cores'])
  File "/Users/nadeau/Desktop/ClownBarf_machine_learning_tracking/OWLS-Autonomy-master/src/tools/visualizer/render.py", line 433, in visualization
    results = list(tqdm(pool.imap(gen_visualizer_frame, mp_batches), total=total, desc='Calculate visualizer frames'))
  File "/Users/nadeau/opt/anaconda3/envs/CB_autonomy/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/nadeau/opt/anaconda3/envs/CB_autonomy/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: Trying to re-register the builtin cmap 'rainbow'.`

**Comment by jakehlee** [comment]
# Triage

## Cause

Attempting to register a new colormap with the name `rainbow` is throwing a `ValueError` since the colormap `rainbow` already exists. 

We didn't hit this because `requirements.txt` specifies `matplotlib~=3.2` and this exception was added in 3.4.0. I'll add updating our package requirements to our near-term roadmap.

https://github.com/matplotlib/matplotlib/blob/9de78eaa6c456d4293e92f4541bc0e8f8e8d50bf/lib/matplotlib/cm.py#L146-L152

https://github.com/matplotlib/matplotlib/commit/1a9dacff1cb0be7bf2f7bc765bb0df6dadcb98ac

## Fix

Refactor the colormap from `rainbow` to `rainbow_mhi`

## ETA

~1 hour, hotfixing internal dev repo now, pushing to public repo afterwards
